targetNamespace: ''
parameters: {}
environment:
  CA_CERT: ${CA_CERT}
  DB_USER: ${DB_USER}
  DB_HOST: ${DB_HOST}
  DB_NAME: ${DB_NAME}
  DB_PASSWORD: ${DB_PASSWORD}
  DB_PORT: ${DB_PORT}
packages:
  - name: sample
    environment: {}
    parameters: {}
    annotations: {}
    actions:
      - name: hello
        binary: false
        main: ''
        runtime: 'nodejs:default'
        web: true
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
